# Generated by Django 6.0.5 on 2026-07-09 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('friendly_name', models.CharField(max_length=120)),
                ('backend_type', models.CharField(choices=[('cloud_api', 'Cloud API'), ('usb_hid', 'USB HID')], max_length=24)),
                ('model', models.CharField(choices=[('delta_3_max_plus', 'DELTA 3 Max Plus (2048 Wh)'), ('delta_pro_3', 'DELTA Pro 3 (4096 Wh)'), ('delta_pro_ultra', 'DELTA Pro Ultra (6000 Wh)'), ('river_3_plus', 'RIVER 3 Plus (286 Wh)')], max_length=64)),
                ('extra_battery_model', models.CharField(blank=True, choices=[('', 'No Extra Battery'), ('delta_3_extra', 'DELTA 3 Extra Battery (1024 Wh)'), ('delta_pro_3_extra', 'DELTA Pro 3 Extra Battery (4096 Wh)'), ('delta_pro_ultra_battery', 'DELTA Pro Ultra Battery (6000 Wh)'), ('river_3_plus_extra', 'RIVER 3 Plus Extra Battery (286 Wh)')], default='', max_length=64)),
                ('polling_interval', models.PositiveIntegerField(default=30)),
                ('grace_period_minutes', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ['friendly_name', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('grid_restored_at', models.DateTimeField(blank=True, null=True)),
                ('power_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutdown_events', to='operations.powerstation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField()),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('shutdown_method', models.CharField(choices=[('ssh_command', 'SSH Command'), ('os_api', 'OS API')], max_length=24)),
                ('is_host', models.BooleanField(default=False)),
                ('power_draw_watts', models.PositiveIntegerField()),
                ('power_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shutdown_targets', to='operations.powerstation')),
            ],
            options={
                'ordering': ['power_station', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShutdownTargetExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('shutdown_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_logs', to='operations.shutdownevent')),
                ('shutdown_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='operations.shutdowntarget')),
            ],
            options={
                'ordering': ['shutdown_event', 'priority', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shutdowntarget',
            constraint=models.UniqueConstraint(fields=('power_station', 'priority'), name='unique_shutdown_priority_per_power_station'),
        ),
    ]
